- name: Configure Windows User and RDP
        shell: powershell
        run: |
          $Password = ConvertTo-SecureString "WindowsPassword123!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $Password

          # السماح بالاتصالات عن بعد
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          
          # تعطيل الـ NLA تماماً ليتوافق مع Windows 7
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
          
          # إجبار السيرفر على استخدام بروتوكول التوافقية القديم (Negotiate) بدلاً من SSL الصارم
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "SecurityLayer" -Value 1

          # تفعيل جدار الحماية للـ RDP
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # تشغيل الخدمة
          Set-Service -Name "TermService" -StartupType Automatic
          Start-Service -Name "TermService"
